// track type 类型
export enum TrackType {
  标签栏 = '标签栏',
  首页 = '首页',
  卡包 = '卡包',
  商城 = '商城',
  我的 = '我的',
  签到 = '签到',
  导航栏 = '导航栏',
  我的兑换 = '我的兑换',
}

// track element
export enum TrackElement {
  视频 = '视频',
  签到 = '签到',
  商城 = '商城',
  我的积分 = '我的积分',
  卡片记录 = '卡片记录',
  隐私条款 = '隐私条款',
  卡片 = '卡片',
  集卡规则 = '集卡规则',
  兑换盲盒 = '兑换盲盒',
  兑换大礼包 = '兑换大礼包',
  签到规则 = '签到规则',
  签到成功 = '签到成功',
  返回上页 = '返回上页',
  前往首页 = '前往首页',
  公众号跳转 = '公众号跳转',
  卡片详情 = '卡片详情',
  卡片赠送 = '卡片赠送',
  卡片索要 = '卡片索要',
  弹框关闭 = '弹框关闭',
  兑换前确认 = '兑换前确认',
  再次扫卡 = '再次扫卡',
  我的卡包 = '我的卡包',
  上一页 = '上一页',
  下一页 = '下一页',
  商品预览 = '商品预览',
  商品兑换 = '商品兑换',
  兑换成功 = '兑换成功',
  确定 = '确定',
  积分规则 = '积分规则',
  状态切换 = '状态切换',
  点击使用 = '点击使用',
  领卡成功 = '领卡成功',
  索取弹框 = '索取弹框',
  慷慨送出 = '慷慨送出',
  赠送弹框 = '赠送弹框',
}

export const TrackMapEN = {
  [TrackType.标签栏]: 'tabbar',
  [TrackType.首页]: 'home',
  [TrackType.卡包]: 'card-package',
  [TrackType.商城]: 'mall',
  [TrackType.我的]: 'mine',
  [TrackType.签到]: 'sign-in',
  [TrackType.导航栏]: 'navigator',
  [TrackType.我的兑换]: 'mine-exchange',
  [TrackElement.视频]: 'video',
  [TrackElement.我的积分]: 'mine-point',
  [TrackElement.卡片记录]: 'card-record',
  [TrackElement.隐私条款]: 'privacy-policy',
  [TrackElement.卡片]: 'card',
  [TrackElement.集卡规则]: 'collect-cards-rule',
  [TrackElement.兑换盲盒]: 'exchange-blind-box',
  [TrackElement.兑换大礼包]: 'exchange-spree',
  [TrackElement.签到规则]: 'sign-in-rule',
  [TrackElement.签到成功]: 'sign-in-sucess',
  [TrackElement.返回上页]: 'back-page',
  [TrackElement.前往首页]: 'go-to-home',
  [TrackElement.公众号跳转]: 'go-to-official-accounts',
  [TrackElement.卡片详情]: 'card-info',
  [TrackElement.卡片赠送]: 'card-give',
  [TrackElement.卡片索要]: 'card-demand',
  [TrackElement.弹框关闭]: 'close-dialog',
  [TrackElement.兑换前确认]: 'confirm-before-exchange',
  [TrackElement.再次扫卡]: 'scan-code-again',
  [TrackElement.我的卡包]: 'mine-card-package',
  [TrackElement.上一页]: 'prev',
  [TrackElement.下一页]: 'next',
  [TrackElement.商品预览]: 'goods-preview',
  [TrackElement.商品兑换]: 'goods-exchange',
  [TrackElement.兑换成功]: 'exchange-success',
  [TrackElement.确定]: 'confirm',
  [TrackElement.积分规则]: 'point-rule',
  [TrackElement.状态切换]: 'status-switch',
  [TrackElement.点击使用]: 'click-use',
  [TrackElement.领卡成功]: 'receive-success',
  [TrackElement.索取弹框]: 'demand-dialog',
  [TrackElement.慷慨送出]: 'send-out',
  [TrackElement.赠送弹框]: 'give-dialog',
}
